---
title: "R Notebook"
output: html_notebook
---

```{r}
installed.packages("QuantPsyc")
library(QuantPsyc)
set.seed(33)
y=rnorm(500,10,1)
x1=rnorm(500,2,.3)
x2=rnorm(500,0,.3)
x3=rnorm(500,3,12)
x4=rnorm(500,100,3)
x5=rnorm(500,14,20)
x6=rnorm(500,30,2)
x7=rnorm(500,-5,100)
x8=rnorm(500,3,1)
x9=rnorm(500,4,1)
x10=rnorm(500,10,.1)
lm_first=lm(y~x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)
summary(lm_first)
print("------- standardized coefficients -------")
summary(lm.beta(lm_first))
print("------- r=andom interaction terms -------")
summary(lm(y~x1+x2+x1*x2+x1*x3+x1*x4++x1*x2*x3+x3+x4+x5+x6+x7+x8+x9+x10))
```

```{r}
#these coefficients are incorrect. Does modeling one Xn work? 
print("---------------")
summary(lm(y~x1))
print("---------------")
summary(lm(y~x2))
print("---------------")
summary(lm(y~x3))
print("---------------")
summary(lm(y~x4))
print("---------------")
summary(lm(y~x5))
print("---------------")
summary(lm(y~x6))
print("---------------")
summary(lm(y~x7))
print("---------------")
summary(lm(y~x8))
print("---------------")
summary(lm(y~x9))
print("---------------")
summary(lm(y~x10))
print("---------------")

```
